version: '3'
services:
  lb:
    image: nginx:alpine
    container_name: myshop-lb
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/lb.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lb-network

networks:
  lb-network:
    driver: bridge
